name: Compilation

on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        runner: [ubuntu-20.04]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout iac-coursework-CI-8
        uses: actions/checkout@v2
        with:
          path: iac-coursework-CI-8
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Create environment
        run: bash <(curl -fsSL https://raw.githubusercontent.com/EIE2-IAC-Labs/Lab0-devtools/main/tools/install.sh)
      - name: Build and Run Simulation
        run: |
          git clone https://github.com/EIE2-IAC-Labs/iac-riscv-cw-8
          chmod +x iac-riscv-cw-8/rtl/doit.sh
          cd iac-riscv-cw-8/rtl
          ./doit.sh
          
  mac_os:
    runs-on: macos-12
    steps:
      - name: Checkout iac-coursework-CI-8
        uses: actions/checkout@v2
        with:
          path: iac-coursework-CI-8
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Create environment
        run: bash <(curl -fsSL https://raw.githubusercontent.com/EIE2-IAC-Labs/Lab0-devtools/main/tools/install.sh)
      - name: Build and Run Simulation
        run: |
          git clone https://github.com/EIE2-IAC-Labs/iac-riscv-cw-8
          chmod +x iac-riscv-cw-8/rtl/doit.sh
          cd iac-riscv-cw-8/rtl
          ./doit.sh
